### ISSUE TITLE
Add "display mode" to ComboBox

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#451]
1/17/19 phet-io meeting, requested by @kathy-phet:

Add `{BooleanProperty} singleItemDisplayProperty`, default `false`.  Hides the arrow and vertical separator on the ComboBoxButton, and set's `pickable: false` on the ComboBox.

**Comment by pixelzoom** [comment]
This will involve instrumenting ComboBoxButton, which is currently not implemented.

**Comment by pixelzoom** [comment]
Implemented in the above commits.  

While implementing this, I decided that `displayOnlyProperty` was a better name.  Here it is in ComboBoxButton:

```js
      this.displayOnlyProperty = new BooleanProperty( false, {
        tandem: options.tandem.createTandem( 'displayOnlyProperty' ),
        phetioDocumentation: 'disables interaction with the ComboBox and makes it appear like value display'
      } );
```

Here's how it looks in Studio with Beer's Law Lab.  First with `false` (the normal state):

![screenshot_962](https://user-images.githubusercontent.com/3046552/51342336-e13ba880-1a50-11e9-8267-b542cf3795b8.png)

Here's how it looks where set to `true`.  The arrow and vertical separator are hidden, and the combo box is not interactive.

![screenshot_961](https://user-images.githubusercontent.com/3046552/51342355-ea2c7a00-1a50-11e9-9dc4-63a41748d6aa.png)

@ariel-phet please assigning someone to review.

**Comment by pixelzoom** [comment]
phetioDocumentation was revised to:

```js
phetioDocumentation:
  'disables interaction with the ComboBox and makes it appear like a display that shows the current selection'
```

**Comment by samreid** [comment]
@chrisklus and I reviewed and it looks great, we made minor modifications above.  Back to @pixelzoom to sign off on the minor changes.  Close if all is well.

**Comment by pixelzoom** [comment]
👍  

@samreid  FYI, it looks like a bunch of commit above are for some other issue with title "Remove whitespace from tandem strings".  Up to you whether to tag those commits with the correct issue number.

Closing.

**Comment by pixelzoom** [comment]
Reopening.  I think this Property may be misplaced.  It should probably be a Property of ComboBox, not ComboBoxButton.  And in addition to changing the look of ComboBoxButton, it should hide the listBox.

@samreid your opinion?

**Comment by pixelzoom** [comment]
`displayOnlyProperty` has been moved from ComboBoxButton to ComboBox.  Please re-review.

Here's how it looks in Studio with Beer's Law Lab when set to `false` (normal ComboBox operation):

<img width="832" alt="screenshot_1002" src="https://user-images.githubusercontent.com/3046552/51456027-63ee8d00-1d09-11e9-9fc5-f5795bd28056.png">

Here's how it looks where set to `true`. Note that the listbox has been hidden, the button's arrow and vertical separator are hidden, and the entire ComboBox is `pickable:false`.

<img width="835" alt="screenshot_1003" src="https://user-images.githubusercontent.com/3046552/51456044-710b7c00-1d09-11e9-932c-ffdfc20f5bf3.png">

**Comment by zepumph** [comment]
Everything looks good to me. I like putting it directly on the ComboBox.

I wasn't quite sure why we aren't resetting this property on reset? It makes sense to me why we may think that it is nice to not reset so that a client doesn't have to invoke a call again on reset to turn the combo box to display mode. I am worried that this is a new convention, that we don't do anywhere else in the project. Currently our "solution" is explained at the bottom of the wrapper index:

>Simulation "Reset All" buttons can overwrite certain kinds of customizations when restoring the simulation to its initial state. If you don't need the Reset All button, then you can hide it using the API with NodeIO.visibleProperty.setValue(). If the ResetAllButton is made invisible, invoking customizations on the simulation in the Client.onSimInitialized() listener is enough. Otherwise, you will need to add a listener to the Reset All button to apply the customizations on the button fire event. This can also be done successfully in Client.onSimInitialized(). Note that it is recommended that you add Client callbacks (like onSimInitialized and onPhetioInitialized) from the launchSim options.


While this isn't the greatest solution, it is general. I would recommend making `displayOnlyProperty` reset with the rest of combo box. If there are disagreements about this, then I think we should open another issue to discuss this topic in general. Referencing https://github.com/phetsims/phet-io/issues/584 here is probably worth while too.

**Comment by pixelzoom** [comment]
Zoom discussion with @zepumph and @samreid:

`displayOnlyProperty` is not part of the user experience, it's not something that the user can change, and it therefore shouldn't be changeable via Reset All.

There's no advantage to wiring `displayOnlyProperty` into Reset All, although that would work OK since the PhET-iO wrapper client uses the customization callback is used on startup and Reset All.  In order to wire `displayOnlyProperty` into Reset All, we'd need to add a `reset` method to all UI components between the ResetAllButton and the ComboBox.  

This is the same policy that we've had for many years for (e.g.) customizing text elements - they do not reset on Reset All.  

So in general, Properties that exist solely for PhET-iO customization should not be wired into Reset All.  Assigning to @zepumph to make a note about this in PhET-iO Instrumentation doc.

**Comment by zepumph** [comment]
Over in https://github.com/phetsims/sun/issues/914, @samreid and I realized that this "displayOnly" characteristic was not implemented with respect to the PDOM.

**Comment by samreid** [comment]
I believe this patch is all we need:

<details>

```diff

Subject: [PATCH] Update range for TEMPERATURE_CELSIUS_LATITUDE, see https://github.com/phetsims/least-squares-regression/issues/92
---
Index: js/ComboBox.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/ComboBox.ts b/js/ComboBox.ts
--- a/js/ComboBox.ts	(revision 46abda161799f96f2d7c6c0c25daab94b138f973)
+++ b/js/ComboBox.ts	(date 1734987456575)
@@ -458,6 +458,12 @@
 
     // support for binder documentation, stripped out in builds and only runs when ?binder is specified
     assert && window.phet?.chipper?.queryParameters?.binder && InstanceRegistry.registerDataURL( 'sun', 'ComboBox', this );
+
+    // TODO: Remove this test harness, see https://github.com/phetsims/sun/issues/451
+    // eslint-disable-next-line phet/bad-sim-text
+    setInterval( () => {
+      this.displayOnlyProperty.value = !this.displayOnlyProperty.value;
+    }, 5000 );
   }
 
   public override dispose(): void {
Index: js/ComboBoxButton.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/ComboBoxButton.ts b/js/ComboBoxButton.ts
--- a/js/ComboBoxButton.ts	(revision 46abda161799f96f2d7c6c0c25daab94b138f973)
+++ b/js/ComboBoxButton.ts	(date 1734987428631)
@@ -313,11 +313,12 @@
   /**
    * Sets the button to look like a value display instead of a combo box button.
    * See https://github.com/phetsims/sun/issues/451
-   * TODO: What does the PDOM look like when set to displayOnly? https://github.com/phetsims/sun/issues/451
    */
   public setDisplayOnly( displayOnly: boolean ): void {
     this.arrow.visible = !displayOnly;
     this.separatorLine.visible = !displayOnly;
+
+    this.tagName = displayOnly ? 'p' : 'button';
   }
 
   /**


```

</details>

Note this patch has a test harness in it, you can launch in http://localhost/center-and-variability/center-and-variability_a11y_view.html?brand=phet&ea&debugger, open the preferences => Simulation, and see the a11y view change from button to p.

@zepumph does this look right to you? Anything else for this issue? If you commit, please remove the test harness tagged for removal with a TODO.

**Comment by samreid** [comment]
UPDATE: Please see further investigation in https://github.com/phetsims/sun/issues/617#issuecomment-2566027482

**Comment by zepumph** [comment]
I got to a commit point. I was able to test that this sounds good for nvda, and that studio correctly behaves when toggling displayOnly mode.

Here is the test code I used at the bottom of the ComboBox constructor:

```

    const oldX = window.x;
    window.x = () => {
      oldX && oldX();
      this.displayOnlyProperty.value = !this.displayOnlyProperty.value
    };
```

**Comment by samreid** [comment]
I reviewed the commit and it looks good to go, closing.

**Comment by zepumph** [comment]
I see this assertion in Buoyancy phet-io fuzzing that is likely from this:

```
buoyancy-basics : phet-io-fuzz : unbuilt
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1736251271603/buoyancy-basics/buoyancy-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1736251271603%22%2C%22timestamp%22%3A1736255646199%7D&ea&brand=phet-io&phetioStandalone&fuzz&phetioLogFuzzedValues
ERROR: QUERY: ea&brand=phet-io&phetioStandalone&fuzz&phetioLogFuzzedValues
Uncaught Error: Assertion failed: trying to set focus on a Node that is not focusable
STACK: Error: Assertion failed: trying to set focus on a Node that is not focusable
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1736251271603/assert/js/assert.js:45:21)
    at assert (../../../../../../../scenery/js/accessibility/pdom/ParallelDOM.ts:800:16)
    at focus (../../../../../sun/js/ComboBox.ts:314:20)
    at focusButtonCallback (../../../../../sun/js/ComboBoxListBox.ts:119:6)
    at apply (../../../../../tandem/js/PhetioAction.ts:162:16)
    at execute (../../../../../sun/js/ComboBoxListBox.ts:144:19)
    at inputEvent (../../../../../../scenery/js/input/Input.ts:1875:91)
    at dispatchToListeners (../../../../../../scenery/js/input/Input.ts:1914:11)
    at dispatchToTargets (../../../../../../scenery/js/input/Input.ts:1828:9)
    at dispatchEvent (../../../../../../scenery/js/input/Input.ts:1628:9)
    at upEvent (../../../../../../scenery/js/input/Input.ts:395:11)
    at apply (../../../../../tandem/js/PhetioAction.ts:162:16)
    at execute (../../../../../../scenery/js/input/Input.ts:1194:23)
    at mouseUp (../../../../../../scenery/js/input/InputFuzzer.js:275:26)
    at mouseToggle (../../../../../../scenery/js/input/InputFuzzer.js:40:11)
    at action (../../../../../../scenery/js/input/InputFuzzer.js:107:6)
    at fuzzEvents (../../../../../joist/js/SimDisplay.ts:221:23)
    at fuzzInputEvents (../../../../../joist/js/Sim.ts:1146:42)
    at fuzzFrame (../../../../../joist/js/Sim.ts:1047:11)

**Comment by zepumph** [comment]
I think that will clean up CT, but I'll check back in a few columns.

**Comment by zepumph** [comment]
All fixed up, and I tested manually also by toggling displayOnly mode in studio when the list box was open. Closing
