### ISSUE TITLE
Remove data from Checkbox toggleAction

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#581]
Related to https://github.com/phetsims/sun/issues/559#issuecomment-589478249

**Comment by zepumph** [comment]
We discussed that over in ToggleSwitch, it didn't make sense to expose the Property details to the UI action. We should be consistent and remove this data from checkbox's toggleAction as well.

**Comment by zepumph** [comment]
Implemented above. @chrisklus please review.

**Comment by pixelzoom** [comment]
This is failing in CT.  Programming error on Checkbox.js line 125: `toggleAction.execute();`  This needs to have `newValue` arg or the BooleanProperty will be set to `undefined`.  This causes every checkbox to fail the first time it's pushed. Did you test before pushing this?

```
hookes-law : phet-io-mirror-inputs-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584648973117/phet-io-wrappers/mirror-inputs/?sim=hookes-law&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: value should have typeof boolean, value=undefined
Error: Assertion failed: value should have typeof boolean, value=undefined
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584648973117/assert/js/assert.js?bust=1584651020967:22:13)
    at Object.isValueValidValueType (https://bayes.colorado.edu/continuous-testing/snapshot-1584648973117/axon/js/ValidatorDef.js:321:39)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1584648973117/axon/js/ValidatorDef.js:257:28)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1584648973117/axon/js/validate.js:27:18)
    at BooleanProperty.Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1584648973117/axon/js/Property.js:138:32)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1584648973117/axon/js/Property.js:167:29)
    at BooleanProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1584648973117/axon/js/Property.js:346:32)
    at Checkbox.Action.parameters (https://bayes.colorado.edu/continuous-testing/snapshot-1584648973117/sun/js/Checkbox.js:72:20)
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584648973117/axon/js/Action.js:224:18)
    at Object.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1584648973117/sun/js/Checkbox.js:125:22)
id: Bayes Chrome
Approximately 3/19/2020, 2:16:13 PM
```

**Comment by samreid** [comment]
The value still needs to pass through the `Action`, so I marked it as `phetioPrivate` and ran `grunt update` on every sim.  Only States of Matter (and basics) changed.  @zepumph can you please review?

**Comment by pixelzoom** [comment]
Thanks for fixing @samreid.

Inspecting the commit, I see this in Checkbox.js:

`parameters: [ { phetioPrivate: true, isValidValue: value => value === true || value === false } ],`

Having to test for `true` and `false` is unfortunate, and not typical of what I'd expect to see in a validator.  Is this not possible?

`parameters: [ { phetioPrivate: true, valueType: 'boolean' } ],`

**Comment by samreid** [comment]
That's much better, thanks!

**Comment by pixelzoom** [comment]
Here's what it was prior to @zepumph's commit:

`parameters: [ { name: 'isChecked', phetioType: BooleanIO } ],`

**Comment by samreid** [comment]
`valueType` will be better since data should not be instrumented for phet-io

**Comment by zepumph** [comment]
I'm so terribly sorry to commit such a bug. 

Thanks for fixing it @samreid.

I felt like a key reason for this issue was to get rid of that parameter. This seems simpler to me, but let me know if you disagree. Please review.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/sun/commit/e1abf4da29c39db5e2762cc88d2643296d1790d2 does seem better to me.

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
