### ISSUE TITLE
class NumberPicker not compatible with MutableOptionsNode

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#627]
After work in https://github.com/phetsims/scenery/issues/1078, CT is showing:

```
proportion-playground : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600456397316/proportion-playground/proportion-playground_en.html?continuousTest=%7B%22test%22%3A%5B%22proportion-playground%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1600456397316%22%2C%22timestamp%22%3A1600457755752%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Class constructor NumberPicker cannot be invoked without 'new'
TypeError: Class constructor NumberPicker cannot be invoked without 'new'
at new MutableOptionsNodeConstructor (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600456397316/sun/js/MutableOptionsNode.js:65:17)
at MutableOptionsNode.replaceCopy (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600456397316/sun/js/MutableOptionsNode.js:87:21)
at new Multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600456397316/axon/js/Multilink.js:61:16)
at Function.multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600456397316/axon/js/Property.js:522:12)
at new MutableOptionsNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600456397316/sun/js/MutableOptionsNode.js:72:29)
at createPickers (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600456397316/proportion-playground/js/common/view/SceneRatioControl.js:67:20)
at NecklaceControl.SceneRatioControl [as constructor] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600456397316/proportion-playground/js/common/view/SceneRatioControl.js:94:21)
at new NecklaceControl (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600456397316/proportion-playground/js/common/view/necklace/NecklaceControl.js:24:21)
at new NecklaceSceneNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600456397316/proportion-playground/js/common/view/necklace/NecklaceSceneNode.js:34:31)
at new ProportionScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600456397316/proportion-playground/js/common/view/ProportionScreenView.js:44:5)
id: Bayes Chrome
Snapshot from 9/18/2020, 1:13:17 PM
```

**Comment by samreid** [comment]
I switched to use Reflect.construct, as suggested in the comments and it appears to be working OK.  @jonathanolson can you please review?

**Comment by pixelzoom** [comment]
See also the problem with MutableOptionsNode in https://github.com/phetsims/masses-and-springs/issues/363. Related? Resolvable at the same time?

**Comment by samreid** [comment]
Yes, that seems like it is caused by the same problem, and likely that the commit will help that case too.

**Comment by jonathanolson** [comment]
It wasn't creating a type anymore effectively (and the inherit wasn't doing anything), so I cleaned this up to a `_createInstance` function that is streamlined. @samreid can you review my changes? Otherwise looks good to go.

**Comment by samreid** [comment]
The function looks much better, thanks!  Closing.
