### ISSUE TITLE
CT should not be called if disposed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/sun#636]
Number of sims in CT with similar issues:
```
build-an-atom : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601618609613/build-an-atom/build-an-atom_en.html?continuousTest=%7B%22test%22%3A%5B%22build-an-atom%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1601618609613%22%2C%22timestamp%22%3A1601624496328%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601618609613/assert/js/assert.js:22:13)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601618609613/axon/js/TinyEmitter.js:53:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601618609613/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601618609613/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601618609613/axon/js/Emitter.js:60:19)
at downPropertyObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601618609613/sun/js/buttons/PushButtonModel.js:91:36)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601618609613/axon/js/TinyEmitter.js:71:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601618609613/axon/js/Property.js:280:25)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601618609613/axon/js/Property.js:178:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601618609613/sun/js/buttons/ButtonModel.js:158:25
id: Bayes Chrome
Snapshot from 10/2/2020, 12:03:29 AM
```
Seems related to https://github.com/phetsims/sun/issues/631

**Comment by zepumph** [comment]
This is from #631 and https://github.com/phetsims/sun/issues/635 while I was cleaning up some stuff in ButtonModel's dispose hierarchy. Specifically from https://github.com/phetsims/sun/commit/87e0d36e8eba662710fb4a5f9d408d37d241c62f, where I made sure that produceSoundEmitter was disposed by ButtonModel instead of unlinked from in all subtypes that added listeners. 

@jbphet the above commit fixes CT errors and makes sure that a disposed "produceSoundEmitter" doesn't get emitted on. Can you please review this in correlation with https://github.com/phetsims/sun/issues/635

**Comment by jbphet** [comment]
Looks fine to me.  Closing.
