### ISSUE TITLE
CT Designed api changes detected

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/sun#711]
```
sun : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625751891889/sun/sun_en.html?continuousTest=%7B%22test%22%3A%5B%22sun%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1625751891889%22%2C%22timestamp%22%3A1625753292975%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI
Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

sun.componentsScreen.view.demoHSlider.enabledProperty.phetioReadOnly changed from false to true

sun.componentsScreen.view.demoVSlider.enabledProperty.phetioReadOnly changed from false to true
Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

sun.componentsScreen.view.demoHSlider.enabledProperty.phetioReadOnly changed from false to true

sun.componentsScreen.view.demoVSlider.enabledProperty.phetioReadOnly changed from false to true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625751891889/assert/js/assert.js:25:13)
at XMLHttpRequest.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625751891889/phet-io/js/phetioEngine.js:312:23)
id: Bayes Chrome
Snapshot from 7/8/2021, 7:44:51 AM
```

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/phet-io/issues/1799#issuecomment-875810345, @zepumph said:
> This is pretty easy to test. I'll commit a breaking change to sun, which is being tested as part of the `api-stable` list. I can locally see that the error occurs when running `?phetioCompareAPI`. I'll commit and check back to see if CT catches it.

So it looks like CT is catching it :)

Perhaps @zepumph has not backed out this breaking change.  Assigning to him.

**Comment by zepumph** [comment]
Commit reverted in https://github.com/phetsims/phet-io/issues/1799. Closing
