### ISSUE TITLE
API change for `slider.enabledProperty`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#735]
Several sims have been failing CT due to PhET-iO API changes to Slider `enabledProperty`. For example:

```
molecule-polarity : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643631899761/molecule-polarity/molecule-polarity_en.html?continuousTest=%7B%22test%22%3A%5B%22molecule-polarity%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643631899761%22%2C%22timestamp%22%3A1643637936709%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

PhET-iO Element missing: moleculePolarity.threeAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.enabledProperty

PhET-iO Element missing: moleculePolarity.threeAtomsScreen.view.electronegativityPanels.atomBElectronegativityPanel.slider.enabledProperty

PhET-iO Element missing: moleculePolarity.threeAtomsScreen.view.electronegativityPanels.atomCElectronegativityPanel.slider.enabledProperty

PhET-iO Element missing: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.enabledProperty

PhET-iO Element missing: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomBElectronegativityPanel.slider.enabledProperty
Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

PhET-iO Element missing: moleculePolarity.threeAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.enabledProperty

PhET-iO Element missing: moleculePolarity.threeAtomsScreen.view.electronegativityPanels.atomBElectronegativityPanel.slider.enabledProperty

PhET-iO Element missing: moleculePolarity.threeAtomsScreen.view.electronegativityPanels.atomCElectronegativityPanel.slider.enabledProperty

PhET-iO Element missing: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomAElectronegativityPanel.slider.enabledProperty

PhET-iO Element missing: moleculePolarity.twoAtomsScreen.view.electronegativityPanels.atomBElectronegativityPanel.slider.enabledProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643631899761/assert/js/assert.js:25:13)
at XMLHttpRequest.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643631899761/chipper/dist/js/phet-io/js/phetioEngine.js:345:23)
id: Bayes Chrome
Snapshot from 1/31/2022, 5:24:59 AM
```

There have been no sim-specific changes to the sims that I’m responsible for. 

I see changes to AccessibleSlider and AccessibleValueHandler by @mjkauzmann that seem to coincide with the appearance of this problem. For example https://github.com/phetsims/sun/commit/1ad9e76414658b3797009662e651d3d41b48d34a and https://github.com/phetsims/sun/commit/877f09991f4ae29029c2a7c8215d814318b6a91d.

If this was an intentional change, please summarize "why", and update PhET-iO APIs.  If it was unintentional, please correct the regression.

**Comment by zepumph** [comment]
Please also note another, similar change from this slider work over in https://github.com/phetsims/scenery-phet/issues/721.

**Comment by zepumph** [comment]
CT is clear
