### ISSUE TITLE
CT: Cannot set swap out a PhET-iO instrumented targetProperty for an uninstrumented one

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#765]
This started immediately after @samreid pushed https://github.com/phetsims/sun/commit/d2e9d3c15f8697543213dff713dbc7670b931374.

```
sun : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654805982023/sun/sun_en.html?continuousTest=%7B%22test%22%3A%5B%22sun%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654805982023%22%2C%22timestamp%22%3A1654810366740%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Uncaught Error: Assertion failed: Cannot set swap out a PhET-iO instrumented targetProperty for an uninstrumented one
Error: Assertion failed: Cannot set swap out a PhET-iO instrumented targetProperty for an uninstrumented one
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654805982023/assert/js/assert.js:28:13)
at assert (TinyForwardingProperty.ts:74:55)
at setTargetProperty (Node.ts:4196:33)
at setEnabledProperty (Node.ts:4203:9)
at (ComponentsScreenView.ts:305:2)
at demoSlider (ComponentsScreenView.ts:252:9)
at createNode (DemosScreenView.ts:73:25)
at Array.forEach
at forEach (DemosScreenView.ts:72:12)
at (ComponentsScreenView.ts:57:4)
id: Bayes Puppeteer
Snapshot from 6/9/2022, 2:19:42 PM
```

**Comment by samreid** [comment]
Fixed, closing.
