### ISSUE TITLE
CT: Designed API changes detected...

### ISSUE THREAD

**Issue by jbphet** [phetsims/sun#766]
CT is currently showing the error below.  I tried to remedy the situation using `grunt generate-phet-io-api` but it didn't seem to change anything.  Assigning to @samreid, since he made phet-io related commits to `HSlider` yesterday, and the error seems potentially related.

```
sun : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654874958908/sun/sun_en.html?continuousTest=%7B%22test%22%3A%5B%22sun%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654874958908%22%2C%22timestamp%22%3A1654878225831%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

PhET-iO Element missing: sun.componentsScreen.view.demoHSlider.enabledProperty

PhET-iO Element missing: sun.componentsScreen.view.demoVSlider.enabledProperty
Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654874958908/assert/js/assert.js:28:13)
at assert (phetioEngine.js:333:22)
id: Bayes Puppeteer
Snapshot from 6/10/2022, 9:29:18 AM
```

**Comment by samreid** [comment]
I regenerated the phet-io api, which removed the enabled properties and added something new for the carousel and/or combo box.  Closing.
