### ISSUE TITLE
CT Designed API changes detected, please roll them back or revise the reference API:

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/sun#786]
```
sun : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661915268622/sun/sun_en.html?continuousTest=%7B%22test%22%3A%5B%22sun%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661915268622%22%2C%22timestamp%22%3A1661942869972%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

sun.general.model.displayedSimNameProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":"sun demo"}
actual:
{"value":"‪sun demo‬","validValues":null,"units":null}

sun.general.model.simInfo._data.initialState differs.
Expected:
{"checkIE11StencilSupport":null,"dataStreamVersion":"1.0.0","flags":null,"isWebGLSupported":null,"language":null,"phetioCommandProcessorProtocol":"1.0.0","pixelRatio":null,"randomSeed":null,"referrer":null,"repoName":"sun","screenPropertyValue":"sun.homeScreen","screens":[{"name":"Home","phetioID":"sun.homeScreen"},{"name":"Buttons","phetioID":"sun.buttonsScreen"},{"name":"Components","phetioID":"sun.componentsScreen"},{"name":"Dialogs","phetioID":"sun.dialogsScreen"},{"name":"Layout","phetioID":"sun.layoutScreen"}],"simName":"sun demo","simVersion":null,"url":null,"userAgent":null,"window":null,"wrapperMetadata":null}
actual:
{"simName":"‪sun demo‬","screens":[{"name":"‪Home‬","phetioID":"sun.homeScreen"},{"name":"Buttons","phetioID":"sun.buttonsScreen"},{"name":"Components","phetioID":"sun.componentsScreen"},{"name":"Dialogs","phetioID":"sun.dialogsScreen"},{"name":"Layout","phetioID":"sun.layoutScreen"}],"repoName":"sun","screenPropertyValue":"sun.homeScreen","dataStreamVersion":"1.0.0","phetioCommandProcessorProtocol":"1.0.0","simVersion":null,"wrapperMetadata":null,"randomSeed":null,"url":null,"userAgent":null,"window":null,"referrer":null,"language":null,"pixelRatio":null,"isWebGLSupported":null,"checkIE11StencilSupport":null,"flags":null}

sun.general.model.simNameProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":"sun demo"}
actual:
{"value":"‪sun demo‬","validValues":null,"units":null}

Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661915268622/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:365:22)
id: Bayes Puppeteer
Snapshot from 8/30/2022, 9:07:48 PM
```

**Comment by jbphet** [comment]
I just met to discuss with with @zepumph, and the problem was related to recent changes to add directional marks to strings.  He has committed changes that are expected to fix it.  I'll monitor CT and close this issue if and when it looks clear.

**Comment by jbphet** [comment]
The last round of CT, which was from 10:35 today, was clear for sun, so I think it's now safe to close this issue.
