### ISSUE TITLE
Carousel.ts:308 Uncaught TypeError: alignGroup.getMaxSizeProperty is not a function

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#827]
Related to https://github.com/phetsims/sun/issues/814 ...

sun demo fails to start:

```
Carousel.ts:308 Uncaught TypeError: alignGroup.getMaxSizeProperty is not a function
    at new Carousel (Carousel.ts:308:16)
    at new CarouselComboBox (CarouselComboBox.ts:133:22)
    at new DemosScreenView (DemosScreenView.ts:120:30)
    at new ButtonsScreenView (ButtonsScreenView.ts:37:5)
    at ButtonScreen.name [as createView] (sun-main.ts:47:13)
    at ButtonScreen.initializeView (Screen.ts:306:23)
    at Array.<anonymous> (Sim.ts:890:16)
    at Sim.ts:898:25
Carousel @ Carousel.ts:308
CarouselComboBox @ CarouselComboBox.ts:133
DemosScreenView @ DemosScreenView.ts:120
ButtonsScreenView @ ButtonsScreenView.ts:37
ButtonScreen.name @ sun-main.ts:47
initializeView @ Screen.ts:306
(anonymous) @ Sim.ts:890
(anonymous) @ Sim.ts:898
```

**Comment by pixelzoom** [comment]
number-play, function-builder, and other sims that use Carousel also fail to start with the same error message.  I've done a pull-all, all repos on my working copy are on 'master', and transpiler.js is running.

**Comment by pixelzoom** [comment]
I had an unintentional local change to Text that was blocking git pull for scenery.  @samreid helped me figure this out, thanks! Closing.
