### ISSUE TITLE
CT Error: Pointer should be assigned

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/sun#875]
I am seeing this in fourier-making-waves, but do not believe it is a sim problem. Seems to only happen for test `?: interactive-description-fuzz-fuzzBoard-combo`.

```
fourier-making-waves : interactive-description-fuzz-fuzzBoard-combo : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1708705610343/fourier-making-waves/fourier-making-waves_en.html?continuousTest=%7B%22test%22%3A%5B%22fourier-making-waves%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1708705610343%22%2C%22timestamp%22%3A1708706109408%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard
Uncaught Error: Assertion failed: Pointer should be assigned
Error: Assertion failed: Pointer should be assigned
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1708705610343/assert/js/assert.js:28:13)
at assert (AccessibleValueHandler.ts:990:16)
at _onInteractionEnd (AccessibleValueHandler.ts:863:17)
at inputEvent (Input.ts:1907:69)
at dispatchToListeners (Input.ts:1947:11)
at dispatchToTargets (Input.ts:1857:9)
at dispatchEvent (Input.ts:1123:11)
at dispatchPDOMEvent (Input.ts:822:20)
at apply (PhetioAction.ts:162:16)
at execute (Input.ts:1613:21)
```

There are many components using AccessibleSlider in that sim, that may be why it is only showing up there for now.

This assertion was added for changes from https://github.com/phetsims/scenery/issues/1596.

**Comment by jessegreenberg** [comment]
Here is a more detailed stack trace after hitting this locally:

![image](https://github.com/phetsims/sun/assets/6396244/cf144216-86d7-45e6-8ffb-9f503391bb10)

**Comment by jessegreenberg** [comment]
The above commit should fix this. Its just graceful in that if we get a `keyup` event after an interrupt, we don't try to do "interaction end" work twice.

I can no longer hit this assertion locally and I let ~30 sims run through local fuzzing with `?fuzz&fuzzBoard`.

Ill let CT run with this change for a few columns before closing.

**Comment by jessegreenberg** [comment]
CT has run for more than 20 columns without this error. It previously could be seen every few columns. Closing.
